In [1]:
import pandas as pd

In [2]:
covid_df= pd.read_csv('Covid_data/owid-covid-data.csv')

In [14]:
north_america_covid_df= covid_df.loc[covid_df['continent']== 'North America']

In [15]:
usa_covid_df= covid_df.loc[covid_df['location']== 'United States']

In [16]:
usa_covid_df

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,population,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million
334627,USA,North America,United States,2020-01-03,NaN,0.0,NaN,NaN,0.0,NaN,...,24.6,NaN,2.77,78.86,0.926,338289856.0,NaN,NaN,NaN,NaN
334628,USA,North America,United States,2020-01-04,NaN,0.0,NaN,NaN,0.0,NaN,...,24.6,NaN,2.77,78.86,0.926,338289856.0,NaN,NaN,NaN,NaN
334629,USA,North America,United States,2020-01-05,NaN,0.0,NaN,NaN,0.0,NaN,...,24.6,NaN,2.77,78.86,0.926,338289856.0,-2771.0,-4.41,-4.41,-8.248447
334630,USA,North America,United States,2020-01-06,NaN,0.0,NaN,NaN,0.0,NaN,...,24.6,NaN,2.77,78.86,0.926,338289856.0,NaN,NaN,NaN,NaN
334631,USA,North America,United States,2020-01-07,NaN,0.0,NaN,NaN,0.0,NaN,...,24.6,NaN,2.77,78.86,0.926,338289856.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
336029,USA,North America,United States,2023-11-05,103436829.0,NaN,NaN,1138309.0,NaN,NaN,...,24.6,NaN,2.77,78.86,0.926,338289856.0,NaN,NaN,NaN,NaN
336030,USA,North America,United States,2023-11-06,103436829.0,NaN,NaN,1138309.0,NaN,NaN,...,24.6,NaN,2.77,78.86,0.926,338289856.0,NaN,NaN,NaN,NaN
336031,USA,North America,United States,2023-11-07,103436829.0,NaN,NaN,1138309.0,NaN,NaN,...,24.6,NaN,2.77,78.86,0.926,338289856.0,NaN,NaN,NaN,NaN
336032,USA,North America,United States,2023-11-08,103436829.0,NaN,NaN,1138309.0,NaN,NaN,...,24.6,NaN,2.77,78.86,0.926,338289856.0,NaN,NaN,NaN,NaN
336033,USA,North America,United States,2023-11-09,103436829.0,NaN,NaN,1138309.0,NaN,NaN,...,24.6,NaN,2.77,78.86,0.926,338289856.0,NaN,NaN,NaN,NaN